### PR TITLE
issue 6 and more : refactor task

### LINKED ISSUE #1: implement a simple pkg update step
for packages reported by Rosa-Luxemburgstiftung-Berlin/ansible-opnsense-checkmk#3 beside usual firmware updates

### LINKED ISSUE #6: implement a dual-step / multi-step upgrade
For example, if the current version is `22.7.11` and `23.1` is released, using `opn_update_force=true` will try to perform a direct upgrade to `23.1` ... and this will not work!
So currently we need 2 ansible runs:

1. using `-e opn_update_desired_version=22.7.11_1` (no reboot required)
2. followed by one using `-e opn_update_desired_version=23.1` or `-e opn_update_force=true`

So as a default we should choose the next available release and using `opn_update_force=true` we should iterate over all available versions ...

### LINKED ISSUE #16: version handling incl. revisions
commit 7cc3907 fixes the version issue #4, but now the version comparison is not honoring the revisions / hot fix releases

### LINKED ISSUE #18: opn_update_desired_version not working as expected
calling role with `opn_update_desired_version=23.7.7` on a *23.7* ends up with *23.7.12_5*

### PR DESCRIPTION
**Pull request by zerwes**
first draft of a more or less automated update using `-e opn_update_force=true`
for now it will just update to the next possible update version, so for some outdated systems this will still require multiple runs.

closes #6
closes #16

### CODE REVIEW

**Comment by zerwes** [comment]
example of a upgrade in 5 steps from 23.7 - 24.7.10_2 using
`ansible-playbook  -e opn_update_force=true ...`

```yaml
ok: [OPNsense2] => {
    "msg": "update performed from 23.7 to 23.7.12_5"
}

ok: [OPNsense2] => {
    "msg": "update performed from 23.7.12.0.5 to 24.1.5_3"
}

ok: [OPNsense2] => {
    "msg": "update performed from 24.1.5.0.3 to 24.1.10_8"
}

ok: [OPNsense2] => {
    "msg": "update performed from 24.1.10.0.8 to 24.7.1"
}

ok: [OPNsense2] => {
    "msg": "update performed from 24.7.1 to 24.7.10_2"
}
```

**Comment by zerwes** [comment]
`-e opn_update_force=true` works as expected and should be the preferred way for now

**Comment by zerwes** [comment]
deprecated opn_update_desired_version (closes #18)

**Comment by zerwes** [comment]
if we deprecate `opn_update_desired_version`, `opn_update_force` should be renamed to `opn_update` ...

**Comment by zerwes** [comment]
renamed PR in order to reflect complete refactoring

**Comment by crpb** [comment]
fyi, worked here aswell. haven't setup an licensed test-vm but i don't think that would be any different.

```
~/ansible/cb/opnsense.test (git)-[main] % ls -1 logs
update-23.1.log
update-23.1.11_2.log
update-23.7.12_5.log
update-24.1.10_8.log
update-24.7.10_2.log
~/ansible/cb/opnsense.test (git)-[main] % grep update/upgrade\  logs/update-23.1.log logs/update-23.1.11_2.log logs/update-23.7.12_5.log logs/update-24.1.10_8.log logs/update-24.7.10_2.log
logs/update-23.1.log:    "msg": "will perform a update/upgrade from 23.1 to 23.1.11_2"
logs/update-23.1.log:    "msg": "update/upgrade performed from 23.1 to 23.1.11_2"
logs/update-23.1.11_2.log:    "msg": "will perform a update/upgrade from 23.1.11.0.2 to 23.7"
logs/update-23.1.11_2.log:    "msg": "update/upgrade performed from 23.1.11_2 to 23.7.5"
logs/update-23.7.12_5.log:    "msg": "will perform a update/upgrade from 23.7.5 to 23.7.12_5"
logs/update-23.7.12_5.log:    "msg": "update/upgrade performed from 23.7.5 to 24.1.5_3"
logs/update-24.1.10_8.log:    "msg": "will perform a update/upgrade from 24.1.5.0.3 to 24.1.10_8"
logs/update-24.1.10_8.log:    "msg": "update/upgrade performed from 24.1.5_3 to 24.7.1"
```

**Comment by zerwes** [comment]
Hello @crpb 
Thank you for the feedback!

**Pull request merged**
